theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
device = "BAT0"

[[block]]
block = "backlight"
step_width = 5

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "time"
interval = 15
format = "%a, %F %H:%M"
