theme = "gruvbox-dark"
icons = "awesome"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"
device = "BAT1"

[[block]]
block = "sound"
step_width = 1

[[block]]
block = "time"
interval = 15
format = "%a, %F %H:%M"
